version: '3.8'
services:
  postgres-db:
    container_name: postgres-db
    image: library/postgres:10.16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dkepr
      POSTGRES_DB: postgres